name: CI (Python Tests)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Read Python version from Pipfile.lock
      - name: Extract Python version
        id: python_version
        run: |
          PYTHON_VERSION=$(jq -r '.default."python_version"' Pipfile.lock)
          echo "python_version=$PYTHON_VERSION" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ steps.python_version.outputs.python_version }}

      - name: Cache pipenv
        uses: actions/cache@v3
        with:
          path: |
            ~/.local/share/virtualenvs
            ~/.cache/pip
          key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev --deploy --ignore-pipfile

      - name: Run tests with coverage
        run: pipenv run pytest --cov=.